// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Meeting struct {
	ID               int64        `db:"id" json:"id"`
	GoogleRecordName string       `db:"google_record_name" json:"google_record_name"`
	GoogleSpaceName  string       `db:"google_space_name" json:"google_space_name"`
	StartedAt        time.Time    `db:"started_at" json:"started_at"`
	EndedAt          sql.NullTime `db:"ended_at" json:"ended_at"`
}

type Participant struct {
	ID                    int64        `db:"id" json:"id"`
	MeetingID             int64        `db:"meeting_id" json:"meeting_id"`
	GoogleParticipantName string       `db:"google_participant_name" json:"google_participant_name"`
	GoogleUserName        string       `db:"google_user_name" json:"google_user_name"`
	DisplayName           string       `db:"display_name" json:"display_name"`
	JoinedAt              time.Time    `db:"joined_at" json:"joined_at"`
	LeftAt                sql.NullTime `db:"left_at" json:"left_at"`
	DurationMinutes       int64        `db:"duration_minutes" json:"duration_minutes"`
}

type Student struct {
	ID              int64  `db:"id" json:"id"`
	Name            string `db:"name" json:"name"`
	GoogleSpaceName string `db:"google_space_name" json:"google_space_name"`
	CycleStartDay   int64  `db:"cycle_start_day" json:"cycle_start_day"`
}
