// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*) FROM students
`

func (q *Queries) CountStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :exec
INSERT INTO students (name, google_space_name, cycle_start_day)
VALUES (?, ?, ?)
`

type CreateStudentParams struct {
	Name            string `db:"name" json:"name"`
	GoogleSpaceName string `db:"google_space_name" json:"google_space_name"`
	CycleStartDay   int64  `db:"cycle_start_day" json:"cycle_start_day"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent, arg.Name, arg.GoogleSpaceName, arg.CycleStartDay)
	return err
}

const deleteStudentsWithoutMeetings = `-- name: DeleteStudentsWithoutMeetings :exec
DELETE FROM students
WHERE NOT EXISTS (
    SELECT 1
    FROM meetings
    WHERE meetings.google_space_name = students.google_space_name
)
`

func (q *Queries) DeleteStudentsWithoutMeetings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStudentsWithoutMeetings)
	return err
}

const getStudent = `-- name: GetStudent :one
SELECT id, name, google_space_name, cycle_start_day
FROM students
WHERE id = ?
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GoogleSpaceName,
		&i.CycleStartDay,
	)
	return i, err
}

const listMeetingParticipants = `-- name: ListMeetingParticipants :many
SELECT id, meeting_id, google_participant_name, google_user_name,
       display_name, joined_at, left_at, duration_minutes
FROM participants
WHERE meeting_id = ?
ORDER BY duration_minutes DESC, display_name COLLATE NOCASE
`

func (q *Queries) ListMeetingParticipants(ctx context.Context, meetingID int64) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.GoogleParticipantName,
			&i.GoogleUserName,
			&i.DisplayName,
			&i.JoinedAt,
			&i.LeftAt,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentMeetings = `-- name: ListStudentMeetings :many
SELECT id, google_record_name, google_space_name, started_at, ended_at
FROM meetings
WHERE google_space_name = ?
  AND started_at >= ?
  AND started_at < ?
  AND ended_at IS NOT NULL
  AND unixepoch(ended_at) - unixepoch(started_at) >= ?4 * 60
ORDER BY started_at DESC
`

type ListStudentMeetingsParams struct {
	GoogleSpaceName    string      `db:"google_space_name" json:"google_space_name"`
	StartedAt          time.Time   `db:"started_at" json:"started_at"`
	StartedAt_2        time.Time   `db:"started_at_2" json:"started_at_2"`
	MinDurationMinutes interface{} `db:"min_duration_minutes" json:"min_duration_minutes"`
}

func (q *Queries) ListStudentMeetings(ctx context.Context, arg ListStudentMeetingsParams) ([]Meeting, error) {
	rows, err := q.db.QueryContext(ctx, listStudentMeetings,
		arg.GoogleSpaceName,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.MinDurationMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meeting
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.GoogleRecordName,
			&i.GoogleSpaceName,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, name, google_space_name, cycle_start_day
FROM students
ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GoogleSpaceName,
			&i.CycleStartDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedSpaces = `-- name: ListUnassignedSpaces :many
SELECT DISTINCT meetings.google_space_name
FROM meetings
LEFT JOIN students ON students.google_space_name = meetings.google_space_name
WHERE students.id IS NULL
ORDER BY meetings.google_space_name
`

func (q *Queries) ListUnassignedSpaces(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var google_space_name string
		if err := rows.Scan(&google_space_name); err != nil {
			return nil, err
		}
		items = append(items, google_space_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :execrows
UPDATE students
SET name = ?, cycle_start_day = ?
WHERE id = ?
`

type UpdateStudentParams struct {
	Name          string `db:"name" json:"name"`
	CycleStartDay int64  `db:"cycle_start_day" json:"cycle_start_day"`
	ID            int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStudent, arg.Name, arg.CycleStartDay, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMeeting = `-- name: UpsertMeeting :one
INSERT INTO meetings (
    google_record_name, google_space_name, started_at, ended_at
) VALUES (?, ?, ?, ?)
ON CONFLICT(google_record_name) DO UPDATE SET
    google_space_name = excluded.google_space_name,
    started_at = excluded.started_at,
    ended_at = COALESCE(excluded.ended_at, meetings.ended_at)
RETURNING id
`

type UpsertMeetingParams struct {
	GoogleRecordName string       `db:"google_record_name" json:"google_record_name"`
	GoogleSpaceName  string       `db:"google_space_name" json:"google_space_name"`
	StartedAt        time.Time    `db:"started_at" json:"started_at"`
	EndedAt          sql.NullTime `db:"ended_at" json:"ended_at"`
}

func (q *Queries) UpsertMeeting(ctx context.Context, arg UpsertMeetingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMeeting,
		arg.GoogleRecordName,
		arg.GoogleSpaceName,
		arg.StartedAt,
		arg.EndedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertParticipant = `-- name: UpsertParticipant :exec
INSERT INTO participants (
    meeting_id, google_participant_name, google_user_name,
    display_name, joined_at, left_at, duration_minutes
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(google_participant_name) DO UPDATE SET
    meeting_id = excluded.meeting_id,
    google_user_name = excluded.google_user_name,
    display_name = excluded.display_name,
    joined_at = excluded.joined_at,
    left_at = excluded.left_at,
    duration_minutes = excluded.duration_minutes
`

type UpsertParticipantParams struct {
	MeetingID             int64        `db:"meeting_id" json:"meeting_id"`
	GoogleParticipantName string       `db:"google_participant_name" json:"google_participant_name"`
	GoogleUserName        string       `db:"google_user_name" json:"google_user_name"`
	DisplayName           string       `db:"display_name" json:"display_name"`
	JoinedAt              time.Time    `db:"joined_at" json:"joined_at"`
	LeftAt                sql.NullTime `db:"left_at" json:"left_at"`
	DurationMinutes       int64        `db:"duration_minutes" json:"duration_minutes"`
}

func (q *Queries) UpsertParticipant(ctx context.Context, arg UpsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, upsertParticipant,
		arg.MeetingID,
		arg.GoogleParticipantName,
		arg.GoogleUserName,
		arg.DisplayName,
		arg.JoinedAt,
		arg.LeftAt,
		arg.DurationMinutes,
	)
	return err
}
