// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const checkStudentExists = `-- name: CheckStudentExists :one
SELECT EXISTS(
    SELECT 1 FROM students WHERE class = ?
)
`

func (q *Queries) CheckStudentExists(ctx context.Context, class string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkStudentExists, class)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createLessonDraft = `-- name: CreateLessonDraft :one
INSERT INTO lesson_drafts (
    source_url, custom_prompt, model, status, created_at
) VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateLessonDraftParams struct {
	SourceUrl    string    `db:"source_url" json:"source_url"`
	CustomPrompt string    `db:"custom_prompt" json:"custom_prompt"`
	Model        string    `db:"model" json:"model"`
	Status       string    `db:"status" json:"status"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateLessonDraft(ctx context.Context, arg CreateLessonDraftParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLessonDraft,
		arg.SourceUrl,
		arg.CustomPrompt,
		arg.Model,
		arg.Status,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMistake = `-- name: CreateMistake :one
INSERT INTO mistakes (
    student_id, source_assignment_id, parent_mistake_id, depth,
    topic, error_reason, status, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateMistakeParams struct {
	StudentID          int64         `db:"student_id" json:"student_id"`
	SourceAssignmentID int64         `db:"source_assignment_id" json:"source_assignment_id"`
	ParentMistakeID    sql.NullInt64 `db:"parent_mistake_id" json:"parent_mistake_id"`
	Depth              int64         `db:"depth" json:"depth"`
	Topic              string        `db:"topic" json:"topic"`
	ErrorReason        string        `db:"error_reason" json:"error_reason"`
	Status             string        `db:"status" json:"status"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
}

// Persist one detected mistake, including its remediation ancestry.
func (q *Queries) CreateMistake(ctx context.Context, arg CreateMistakeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMistake,
		arg.StudentID,
		arg.SourceAssignmentID,
		arg.ParentMistakeID,
		arg.Depth,
		arg.Topic,
		arg.ErrorReason,
		arg.Status,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createStudent = `-- name: CreateStudent :exec
INSERT INTO students (class, name, meeting_code, space_name, cycle_start_day)
VALUES (?, ?, ?, ?, ?)
`

type CreateStudentParams struct {
	Class         string `db:"class" json:"class"`
	Name          string `db:"name" json:"name"`
	MeetingCode   string `db:"meeting_code" json:"meeting_code"`
	SpaceName     string `db:"space_name" json:"space_name"`
	CycleStartDay int64  `db:"cycle_start_day" json:"cycle_start_day"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent,
		arg.Class,
		arg.Name,
		arg.MeetingCode,
		arg.SpaceName,
		arg.CycleStartDay,
	)
	return err
}

const deleteLessonDraft = `-- name: DeleteLessonDraft :exec
DELETE FROM lesson_drafts
WHERE id = ?
`

func (q *Queries) DeleteLessonDraft(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLessonDraft, id)
	return err
}

const getAssignmentByPageID = `-- name: GetAssignmentByPageID :one
SELECT
    a.id,
    a.title,
    a.assignment_type,
    a.status,
    a.assigned_at,
    a.target_page_id,
	a.student_page_web_url,
	a.teacher_page_web_url,
    a.items_json,
    a.origin_mistake_id,
    a.depth,
    s.id AS student_id,
    s.class AS student_class,
    s.name AS student_name,
    s.cycle_start_day AS student_cycle_start_day,
    s.student_workspace_id,
    s.teacher_workspace_id
FROM assignments a
JOIN students s ON s.id = a.assignee_id
WHERE a.target_page_id = ?
`

type GetAssignmentByPageIDRow struct {
	ID                   int64          `db:"id" json:"id"`
	Title                string         `db:"title" json:"title"`
	AssignmentType       string         `db:"assignment_type" json:"assignment_type"`
	Status               string         `db:"status" json:"status"`
	AssignedAt           time.Time      `db:"assigned_at" json:"assigned_at"`
	TargetPageID         string         `db:"target_page_id" json:"target_page_id"`
	StudentPageWebUrl    string         `db:"student_page_web_url" json:"student_page_web_url"`
	TeacherPageWebUrl    string         `db:"teacher_page_web_url" json:"teacher_page_web_url"`
	ItemsJson            string         `db:"items_json" json:"items_json"`
	OriginMistakeID      sql.NullInt64  `db:"origin_mistake_id" json:"origin_mistake_id"`
	Depth                int64          `db:"depth" json:"depth"`
	StudentID            int64          `db:"student_id" json:"student_id"`
	StudentClass         string         `db:"student_class" json:"student_class"`
	StudentName          string         `db:"student_name" json:"student_name"`
	StudentCycleStartDay int64          `db:"student_cycle_start_day" json:"student_cycle_start_day"`
	StudentWorkspaceID   sql.NullString `db:"student_workspace_id" json:"student_workspace_id"`
	TeacherWorkspaceID   sql.NullString `db:"teacher_workspace_id" json:"teacher_workspace_id"`
}

// NEW INFRASTRUCTURE: load Assignment and student by OneNote PageID.
func (q *Queries) GetAssignmentByPageID(ctx context.Context, targetPageID string) (GetAssignmentByPageIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByPageID, targetPageID)
	var i GetAssignmentByPageIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AssignmentType,
		&i.Status,
		&i.AssignedAt,
		&i.TargetPageID,
		&i.StudentPageWebUrl,
		&i.TeacherPageWebUrl,
		&i.ItemsJson,
		&i.OriginMistakeID,
		&i.Depth,
		&i.StudentID,
		&i.StudentClass,
		&i.StudentName,
		&i.StudentCycleStartDay,
		&i.StudentWorkspaceID,
		&i.TeacherWorkspaceID,
	)
	return i, err
}

const getLessonDraft = `-- name: GetLessonDraft :one
SELECT id, source_url, custom_prompt, status, error_message,
       title, created_at, updated_at, model, lesson_data_json
FROM lesson_drafts
WHERE id = ?
`

type GetLessonDraftRow struct {
	ID             int64          `db:"id" json:"id"`
	SourceUrl      string         `db:"source_url" json:"source_url"`
	CustomPrompt   string         `db:"custom_prompt" json:"custom_prompt"`
	Status         string         `db:"status" json:"status"`
	ErrorMessage   string         `db:"error_message" json:"error_message"`
	Title          string         `db:"title" json:"title"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
	Model          string         `db:"model" json:"model"`
	LessonDataJson sql.NullString `db:"lesson_data_json" json:"lesson_data_json"`
}

func (q *Queries) GetLessonDraft(ctx context.Context, id int64) (GetLessonDraftRow, error) {
	row := q.db.QueryRowContext(ctx, getLessonDraft, id)
	var i GetLessonDraftRow
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.CustomPrompt,
		&i.Status,
		&i.ErrorMessage,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.LessonDataJson,
	)
	return i, err
}

const getMistakeByID = `-- name: GetMistakeByID :one
SELECT id, source_assignment_id, parent_mistake_id, depth, topic, error_reason, status, created_at
FROM mistakes
WHERE id = ?
`

type GetMistakeByIDRow struct {
	ID                 int64         `db:"id" json:"id"`
	SourceAssignmentID int64         `db:"source_assignment_id" json:"source_assignment_id"`
	ParentMistakeID    sql.NullInt64 `db:"parent_mistake_id" json:"parent_mistake_id"`
	Depth              int64         `db:"depth" json:"depth"`
	Topic              string        `db:"topic" json:"topic"`
	ErrorReason        string        `db:"error_reason" json:"error_reason"`
	Status             string        `db:"status" json:"status"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
}

// Load one mistake for status transitions.
func (q *Queries) GetMistakeByID(ctx context.Context, id int64) (GetMistakeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMistakeByID, id)
	var i GetMistakeByIDRow
	err := row.Scan(
		&i.ID,
		&i.SourceAssignmentID,
		&i.ParentMistakeID,
		&i.Depth,
		&i.Topic,
		&i.ErrorReason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMistakeWithStudent = `-- name: GetMistakeWithStudent :one
SELECT
    m.id,
    m.student_id,
    m.source_assignment_id,
    m.parent_mistake_id,
    m.depth,
    m.topic,
    m.error_reason,
    m.status,
    m.created_at,
    s.class AS student_class,
    s.name AS student_name,
    s.cycle_start_day AS student_cycle_start_day,
    s.student_workspace_id,
    s.teacher_workspace_id
FROM mistakes m
JOIN students s ON s.id = m.student_id
WHERE m.id = ?
`

type GetMistakeWithStudentRow struct {
	ID                   int64          `db:"id" json:"id"`
	StudentID            int64          `db:"student_id" json:"student_id"`
	SourceAssignmentID   int64          `db:"source_assignment_id" json:"source_assignment_id"`
	ParentMistakeID      sql.NullInt64  `db:"parent_mistake_id" json:"parent_mistake_id"`
	Depth                int64          `db:"depth" json:"depth"`
	Topic                string         `db:"topic" json:"topic"`
	ErrorReason          string         `db:"error_reason" json:"error_reason"`
	Status               string         `db:"status" json:"status"`
	CreatedAt            time.Time      `db:"created_at" json:"created_at"`
	StudentClass         string         `db:"student_class" json:"student_class"`
	StudentName          string         `db:"student_name" json:"student_name"`
	StudentCycleStartDay int64          `db:"student_cycle_start_day" json:"student_cycle_start_day"`
	StudentWorkspaceID   sql.NullString `db:"student_workspace_id" json:"student_workspace_id"`
	TeacherWorkspaceID   sql.NullString `db:"teacher_workspace_id" json:"teacher_workspace_id"`
}

// Load the selected mistake and the student who owns it.
func (q *Queries) GetMistakeWithStudent(ctx context.Context, id int64) (GetMistakeWithStudentRow, error) {
	row := q.db.QueryRowContext(ctx, getMistakeWithStudent, id)
	var i GetMistakeWithStudentRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SourceAssignmentID,
		&i.ParentMistakeID,
		&i.Depth,
		&i.Topic,
		&i.ErrorReason,
		&i.Status,
		&i.CreatedAt,
		&i.StudentClass,
		&i.StudentName,
		&i.StudentCycleStartDay,
		&i.StudentWorkspaceID,
		&i.TeacherWorkspaceID,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM system_settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, class, name, meeting_code, space_name, cycle_start_day, student_workspace_id, teacher_workspace_id
FROM students
WHERE id = ?
`

type GetStudentRow struct {
	ID                 int64          `db:"id" json:"id"`
	Class              string         `db:"class" json:"class"`
	Name               string         `db:"name" json:"name"`
	MeetingCode        string         `db:"meeting_code" json:"meeting_code"`
	SpaceName          string         `db:"space_name" json:"space_name"`
	CycleStartDay      int64          `db:"cycle_start_day" json:"cycle_start_day"`
	StudentWorkspaceID sql.NullString `db:"student_workspace_id" json:"student_workspace_id"`
	TeacherWorkspaceID sql.NullString `db:"teacher_workspace_id" json:"teacher_workspace_id"`
}

func (q *Queries) GetStudent(ctx context.Context, id int64) (GetStudentRow, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	var i GetStudentRow
	err := row.Scan(
		&i.ID,
		&i.Class,
		&i.Name,
		&i.MeetingCode,
		&i.SpaceName,
		&i.CycleStartDay,
		&i.StudentWorkspaceID,
		&i.TeacherWorkspaceID,
	)
	return i, err
}

const listAssignmentsForGrading = `-- name: ListAssignmentsForGrading :many
SELECT
    a.id,
    a.title,
    a.status,
    a.assigned_at,
    a.target_page_id,
	a.student_page_web_url,
	a.teacher_page_web_url,
    a.items_json,
    s.id AS student_id,
    s.name AS student_name
FROM assignments a
JOIN students s ON s.id = a.assignee_id
ORDER BY a.assigned_at DESC
`

type ListAssignmentsForGradingRow struct {
	ID                int64     `db:"id" json:"id"`
	Title             string    `db:"title" json:"title"`
	Status            string    `db:"status" json:"status"`
	AssignedAt        time.Time `db:"assigned_at" json:"assigned_at"`
	TargetPageID      string    `db:"target_page_id" json:"target_page_id"`
	StudentPageWebUrl string    `db:"student_page_web_url" json:"student_page_web_url"`
	TeacherPageWebUrl string    `db:"teacher_page_web_url" json:"teacher_page_web_url"`
	ItemsJson         string    `db:"items_json" json:"items_json"`
	StudentID         int64     `db:"student_id" json:"student_id"`
	StudentName       string    `db:"student_name" json:"student_name"`
}

// NEW UI INFRASTRUCTURE: aggregate assignments for the grading screen.
func (q *Queries) ListAssignmentsForGrading(ctx context.Context) ([]ListAssignmentsForGradingRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsForGrading)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsForGradingRow
	for rows.Next() {
		var i ListAssignmentsForGradingRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.AssignedAt,
			&i.TargetPageID,
			&i.StudentPageWebUrl,
			&i.TeacherPageWebUrl,
			&i.ItemsJson,
			&i.StudentID,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassMeetings = `-- name: ListClassMeetings :many
SELECT id, class, code, started_at, ended_at, duration_minutes
FROM meetings
WHERE class = ?
  AND started_at >= ?
  AND started_at <= ?
  AND duration_minutes >= ?
ORDER BY started_at DESC
`

type ListClassMeetingsParams struct {
	Class           string    `db:"class" json:"class"`
	StartedAt       time.Time `db:"started_at" json:"started_at"`
	StartedAt_2     time.Time `db:"started_at_2" json:"started_at_2"`
	DurationMinutes int64     `db:"duration_minutes" json:"duration_minutes"`
}

func (q *Queries) ListClassMeetings(ctx context.Context, arg ListClassMeetingsParams) ([]Meeting, error) {
	rows, err := q.db.QueryContext(ctx, listClassMeetings,
		arg.Class,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.DurationMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meeting
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.Class,
			&i.Code,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonDrafts = `-- name: ListLessonDrafts :many
SELECT id, source_url, custom_prompt, model, status, error_message,
       title, created_at, updated_at, lesson_data_json
FROM lesson_drafts
ORDER BY created_at DESC
`

type ListLessonDraftsRow struct {
	ID             int64          `db:"id" json:"id"`
	SourceUrl      string         `db:"source_url" json:"source_url"`
	CustomPrompt   string         `db:"custom_prompt" json:"custom_prompt"`
	Model          string         `db:"model" json:"model"`
	Status         string         `db:"status" json:"status"`
	ErrorMessage   string         `db:"error_message" json:"error_message"`
	Title          string         `db:"title" json:"title"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
	LessonDataJson sql.NullString `db:"lesson_data_json" json:"lesson_data_json"`
}

func (q *Queries) ListLessonDrafts(ctx context.Context) ([]ListLessonDraftsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLessonDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonDraftsRow
	for rows.Next() {
		var i ListLessonDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.CustomPrompt,
			&i.Model,
			&i.Status,
			&i.ErrorMessage,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LessonDataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingParticipants = `-- name: ListMeetingParticipants :many
SELECT id, meeting_id, name, first_joined_at, last_left_at, duration_minutes
FROM participants
WHERE meeting_id = ?
ORDER BY duration_minutes DESC, name ASC
`

func (q *Queries) ListMeetingParticipants(ctx context.Context, meetingID int64) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Name,
			&i.FirstJoinedAt,
			&i.LastLeftAt,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMistakeAncestry = `-- name: ListMistakeAncestry :many
WITH RECURSIVE ancestry(id, source_assignment_id, parent_mistake_id, depth, topic, error_reason, status, created_at, distance) AS (
    SELECT m.id, m.source_assignment_id, m.parent_mistake_id, m.depth, m.topic, m.error_reason, m.status, m.created_at, 0
    FROM mistakes m
    WHERE m.id = ?
    UNION ALL
    SELECT parent.id, parent.source_assignment_id, parent.parent_mistake_id, parent.depth,
           parent.topic, parent.error_reason, parent.status, parent.created_at, ancestry.distance + 1
    FROM mistakes parent
    JOIN ancestry ON ancestry.parent_mistake_id = parent.id
)
SELECT id, source_assignment_id, parent_mistake_id, depth, topic, error_reason, status, created_at
FROM ancestry
WHERE distance > 0
ORDER BY distance DESC
`

type ListMistakeAncestryRow struct {
	ID                 int64         `db:"id" json:"id"`
	SourceAssignmentID int64         `db:"source_assignment_id" json:"source_assignment_id"`
	ParentMistakeID    sql.NullInt64 `db:"parent_mistake_id" json:"parent_mistake_id"`
	Depth              int64         `db:"depth" json:"depth"`
	Topic              string        `db:"topic" json:"topic"`
	ErrorReason        string        `db:"error_reason" json:"error_reason"`
	Status             string        `db:"status" json:"status"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
}

// Load ancestors from root to the direct parent of the requested mistake.
func (q *Queries) ListMistakeAncestry(ctx context.Context, id int64) ([]ListMistakeAncestryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMistakeAncestry, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMistakeAncestryRow
	for rows.Next() {
		var i ListMistakeAncestryRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceAssignmentID,
			&i.ParentMistakeID,
			&i.Depth,
			&i.Topic,
			&i.ErrorReason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMistakesWithStudents = `-- name: ListMistakesWithStudents :many
SELECT
    m.id,
    m.student_id,
    m.source_assignment_id,
    m.parent_mistake_id,
    m.depth,
    m.topic,
    m.error_reason,
    m.status,
    m.created_at,
    s.name AS student_name
FROM mistakes m
JOIN students s ON s.id = m.student_id
ORDER BY s.name ASC, m.created_at DESC
`

type ListMistakesWithStudentsRow struct {
	ID                 int64         `db:"id" json:"id"`
	StudentID          int64         `db:"student_id" json:"student_id"`
	SourceAssignmentID int64         `db:"source_assignment_id" json:"source_assignment_id"`
	ParentMistakeID    sql.NullInt64 `db:"parent_mistake_id" json:"parent_mistake_id"`
	Depth              int64         `db:"depth" json:"depth"`
	Topic              string        `db:"topic" json:"topic"`
	ErrorReason        string        `db:"error_reason" json:"error_reason"`
	Status             string        `db:"status" json:"status"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
	StudentName        string        `db:"student_name" json:"student_name"`
}

// List mistakes together with their student.
func (q *Queries) ListMistakesWithStudents(ctx context.Context) ([]ListMistakesWithStudentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMistakesWithStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMistakesWithStudentsRow
	for rows.Next() {
		var i ListMistakesWithStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SourceAssignmentID,
			&i.ParentMistakeID,
			&i.Depth,
			&i.Topic,
			&i.ErrorReason,
			&i.Status,
			&i.CreatedAt,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentChoices = `-- name: ListStudentChoices :many
SELECT id, name, class, meeting_code, space_name, student_workspace_id, teacher_workspace_id
FROM students
ORDER BY name ASC
`

type ListStudentChoicesRow struct {
	ID                 int64          `db:"id" json:"id"`
	Name               string         `db:"name" json:"name"`
	Class              string         `db:"class" json:"class"`
	MeetingCode        string         `db:"meeting_code" json:"meeting_code"`
	SpaceName          string         `db:"space_name" json:"space_name"`
	StudentWorkspaceID sql.NullString `db:"student_workspace_id" json:"student_workspace_id"`
	TeacherWorkspaceID sql.NullString `db:"teacher_workspace_id" json:"teacher_workspace_id"`
}

// NEW UI INFRASTRUCTURE: populate compact student selectors.
func (q *Queries) ListStudentChoices(ctx context.Context) ([]ListStudentChoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStudentChoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentChoicesRow
	for rows.Next() {
		var i ListStudentChoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Class,
			&i.MeetingCode,
			&i.SpaceName,
			&i.StudentWorkspaceID,
			&i.TeacherWorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsWithStats = `-- name: ListStudentsWithStats :many
SELECT
    s.id,
    s.class,
    s.name,
	s.meeting_code,
	s.space_name,
    s.cycle_start_day,
    COUNT(m.id) AS total_sessions,
    CAST(COALESCE(SUM(m.duration_minutes), 0) AS INTEGER) AS total_duration_minutes
FROM students s
LEFT JOIN meetings m ON s.class = m.class
    AND m.started_at >= ?
    AND m.started_at <= ?
    AND m.duration_minutes >= ?
WHERE s.name LIKE '%' || COALESCE(?, '') || '%'
GROUP BY s.id
ORDER BY s.id ASC
`

type ListStudentsWithStatsParams struct {
	StartedAt       time.Time      `db:"started_at" json:"started_at"`
	StartedAt_2     time.Time      `db:"started_at_2" json:"started_at_2"`
	DurationMinutes int64          `db:"duration_minutes" json:"duration_minutes"`
	Column4         sql.NullString `db:"column_4" json:"column_4"`
}

type ListStudentsWithStatsRow struct {
	ID                   int64  `db:"id" json:"id"`
	Class                string `db:"class" json:"class"`
	Name                 string `db:"name" json:"name"`
	MeetingCode          string `db:"meeting_code" json:"meeting_code"`
	SpaceName            string `db:"space_name" json:"space_name"`
	CycleStartDay        int64  `db:"cycle_start_day" json:"cycle_start_day"`
	TotalSessions        int64  `db:"total_sessions" json:"total_sessions"`
	TotalDurationMinutes int64  `db:"total_duration_minutes" json:"total_duration_minutes"`
}

func (q *Queries) ListStudentsWithStats(ctx context.Context, arg ListStudentsWithStatsParams) ([]ListStudentsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStudentsWithStats,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.DurationMinutes,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsWithStatsRow
	for rows.Next() {
		var i ListStudentsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Class,
			&i.Name,
			&i.MeetingCode,
			&i.SpaceName,
			&i.CycleStartDay,
			&i.TotalSessions,
			&i.TotalDurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAssignment = `-- name: SaveAssignment :one
INSERT INTO assignments (
	title, assignment_type, status, assigned_at, assignee_id, target_page_id, student_page_web_url, teacher_page_web_url, items_json,
    origin_mistake_id, depth
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_page_id) DO UPDATE SET
    title = excluded.title,
    assignment_type = excluded.assignment_type,
    status = excluded.status,
    assigned_at = excluded.assigned_at,
    assignee_id = excluded.assignee_id,
	student_page_web_url = excluded.student_page_web_url,
	teacher_page_web_url = excluded.teacher_page_web_url,
    items_json = excluded.items_json,
    origin_mistake_id = excluded.origin_mistake_id,
    depth = excluded.depth
RETURNING id
`

type SaveAssignmentParams struct {
	Title             string        `db:"title" json:"title"`
	AssignmentType    string        `db:"assignment_type" json:"assignment_type"`
	Status            string        `db:"status" json:"status"`
	AssignedAt        time.Time     `db:"assigned_at" json:"assigned_at"`
	AssigneeID        int64         `db:"assignee_id" json:"assignee_id"`
	TargetPageID      string        `db:"target_page_id" json:"target_page_id"`
	StudentPageWebUrl string        `db:"student_page_web_url" json:"student_page_web_url"`
	TeacherPageWebUrl string        `db:"teacher_page_web_url" json:"teacher_page_web_url"`
	ItemsJson         string        `db:"items_json" json:"items_json"`
	OriginMistakeID   sql.NullInt64 `db:"origin_mistake_id" json:"origin_mistake_id"`
	Depth             int64         `db:"depth" json:"depth"`
}

// NEW INFRASTRUCTURE: insert/update Assignment by OneNote PageID.
func (q *Queries) SaveAssignment(ctx context.Context, arg SaveAssignmentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveAssignment,
		arg.Title,
		arg.AssignmentType,
		arg.Status,
		arg.AssignedAt,
		arg.AssigneeID,
		arg.TargetPageID,
		arg.StudentPageWebUrl,
		arg.TeacherPageWebUrl,
		arg.ItemsJson,
		arg.OriginMistakeID,
		arg.Depth,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO system_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const updateDefaultStudentName = `-- name: UpdateDefaultStudentName :exec
UPDATE students
SET name = CASE
    WHEN ? <> '' THEN ?
    ELSE printf('%s%d', ?, id)
END
WHERE class = ?
  AND (name = ? OR name GLOB ?)
`

type UpdateDefaultStudentNameParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Name    string      `db:"name" json:"name"`
	PRINTF  interface{} `db:"PRINTF" json:"PRINTF"`
	Class   string      `db:"class" json:"class"`
	Name_2  string      `db:"name_2" json:"name_2"`
	Name_3  string      `db:"name_3" json:"name_3"`
}

func (q *Queries) UpdateDefaultStudentName(ctx context.Context, arg UpdateDefaultStudentNameParams) error {
	_, err := q.db.ExecContext(ctx, updateDefaultStudentName,
		arg.Column1,
		arg.Name,
		arg.PRINTF,
		arg.Class,
		arg.Name_2,
		arg.Name_3,
	)
	return err
}

const updateLessonDraftGeneratedContent = `-- name: UpdateLessonDraftGeneratedContent :exec
UPDATE lesson_drafts
SET status = 'completed',
    title = ?,
    teacher_content = ?,
    student_content = ?,
    error_message = '',
    updated_at = ?
WHERE id = ?
`

type UpdateLessonDraftGeneratedContentParams struct {
	Title          string       `db:"title" json:"title"`
	TeacherContent string       `db:"teacher_content" json:"teacher_content"`
	StudentContent string       `db:"student_content" json:"student_content"`
	UpdatedAt      sql.NullTime `db:"updated_at" json:"updated_at"`
	ID             int64        `db:"id" json:"id"`
}

func (q *Queries) UpdateLessonDraftGeneratedContent(ctx context.Context, arg UpdateLessonDraftGeneratedContentParams) error {
	_, err := q.db.ExecContext(ctx, updateLessonDraftGeneratedContent,
		arg.Title,
		arg.TeacherContent,
		arg.StudentContent,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLessonDraftLessonData = `-- name: UpdateLessonDraftLessonData :exec
UPDATE lesson_drafts
SET status = ?,
    title = ?,
    source_url = ?,
    custom_prompt = ?,
    model = ?,
    lesson_data_json = ?,
    error_message = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateLessonDraftLessonDataParams struct {
	Status         string         `db:"status" json:"status"`
	Title          string         `db:"title" json:"title"`
	SourceUrl      string         `db:"source_url" json:"source_url"`
	CustomPrompt   string         `db:"custom_prompt" json:"custom_prompt"`
	Model          string         `db:"model" json:"model"`
	LessonDataJson sql.NullString `db:"lesson_data_json" json:"lesson_data_json"`
	ErrorMessage   string         `db:"error_message" json:"error_message"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
	ID             int64          `db:"id" json:"id"`
}

// NEW INFRASTRUCTURE: persist the structured Lesson as JSON.
func (q *Queries) UpdateLessonDraftLessonData(ctx context.Context, arg UpdateLessonDraftLessonDataParams) error {
	_, err := q.db.ExecContext(ctx, updateLessonDraftLessonData,
		arg.Status,
		arg.Title,
		arg.SourceUrl,
		arg.CustomPrompt,
		arg.Model,
		arg.LessonDataJson,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLessonDraftStatus = `-- name: UpdateLessonDraftStatus :exec
UPDATE lesson_drafts
SET status = ?, error_message = ?, updated_at = ?
WHERE id = ?
`

type UpdateLessonDraftStatusParams struct {
	Status       string       `db:"status" json:"status"`
	ErrorMessage string       `db:"error_message" json:"error_message"`
	UpdatedAt    sql.NullTime `db:"updated_at" json:"updated_at"`
	ID           int64        `db:"id" json:"id"`
}

func (q *Queries) UpdateLessonDraftStatus(ctx context.Context, arg UpdateLessonDraftStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLessonDraftStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLessonDraftUserContent = `-- name: UpdateLessonDraftUserContent :exec
UPDATE lesson_drafts
SET title = ?,
    teacher_content = ?,
    student_content = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateLessonDraftUserContentParams struct {
	Title          string       `db:"title" json:"title"`
	TeacherContent string       `db:"teacher_content" json:"teacher_content"`
	StudentContent string       `db:"student_content" json:"student_content"`
	UpdatedAt      sql.NullTime `db:"updated_at" json:"updated_at"`
	ID             int64        `db:"id" json:"id"`
}

func (q *Queries) UpdateLessonDraftUserContent(ctx context.Context, arg UpdateLessonDraftUserContentParams) error {
	_, err := q.db.ExecContext(ctx, updateLessonDraftUserContent,
		arg.Title,
		arg.TeacherContent,
		arg.StudentContent,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMistake = `-- name: UpdateMistake :execrows
UPDATE mistakes
SET source_assignment_id = ?,
    parent_mistake_id = ?,
    depth = ?,
    topic = ?,
    error_reason = ?,
    status = ?,
    created_at = ?
WHERE id = ?
`

type UpdateMistakeParams struct {
	SourceAssignmentID int64         `db:"source_assignment_id" json:"source_assignment_id"`
	ParentMistakeID    sql.NullInt64 `db:"parent_mistake_id" json:"parent_mistake_id"`
	Depth              int64         `db:"depth" json:"depth"`
	Topic              string        `db:"topic" json:"topic"`
	ErrorReason        string        `db:"error_reason" json:"error_reason"`
	Status             string        `db:"status" json:"status"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
	ID                 int64         `db:"id" json:"id"`
}

// Persist all domain-owned fields after a lifecycle transition.
func (q *Queries) UpdateMistake(ctx context.Context, arg UpdateMistakeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMistake,
		arg.SourceAssignmentID,
		arg.ParentMistakeID,
		arg.Depth,
		arg.Topic,
		arg.ErrorReason,
		arg.Status,
		arg.CreatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateStudent = `-- name: UpdateStudent :execrows
UPDATE students
SET name = ?, cycle_start_day = ?, student_workspace_id = ?, teacher_workspace_id = ?
WHERE id = ?
`

type UpdateStudentParams struct {
	Name               string         `db:"name" json:"name"`
	CycleStartDay      int64          `db:"cycle_start_day" json:"cycle_start_day"`
	StudentWorkspaceID sql.NullString `db:"student_workspace_id" json:"student_workspace_id"`
	TeacherWorkspaceID sql.NullString `db:"teacher_workspace_id" json:"teacher_workspace_id"`
	ID                 int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStudent,
		arg.Name,
		arg.CycleStartDay,
		arg.StudentWorkspaceID,
		arg.TeacherWorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateStudentMeetIdentity = `-- name: UpdateStudentMeetIdentity :exec
UPDATE students
SET meeting_code = ?, space_name = ?
WHERE class = ?
`

type UpdateStudentMeetIdentityParams struct {
	MeetingCode string `db:"meeting_code" json:"meeting_code"`
	SpaceName   string `db:"space_name" json:"space_name"`
	Class       string `db:"class" json:"class"`
}

func (q *Queries) UpdateStudentMeetIdentity(ctx context.Context, arg UpdateStudentMeetIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateStudentMeetIdentity, arg.MeetingCode, arg.SpaceName, arg.Class)
	return err
}

const upsertMeeting = `-- name: UpsertMeeting :one
INSERT INTO meetings (
    class, code, started_at, ended_at, duration_minutes
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(code) DO UPDATE SET
    class = excluded.class,
    started_at = excluded.started_at,
    ended_at = excluded.ended_at,
    duration_minutes = excluded.duration_minutes
RETURNING id
`

type UpsertMeetingParams struct {
	Class           string       `db:"class" json:"class"`
	Code            string       `db:"code" json:"code"`
	StartedAt       time.Time    `db:"started_at" json:"started_at"`
	EndedAt         sql.NullTime `db:"ended_at" json:"ended_at"`
	DurationMinutes int64        `db:"duration_minutes" json:"duration_minutes"`
}

func (q *Queries) UpsertMeeting(ctx context.Context, arg UpsertMeetingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMeeting,
		arg.Class,
		arg.Code,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMinutes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertParticipant = `-- name: UpsertParticipant :exec
INSERT INTO participants (
    meeting_id, name, first_joined_at, last_left_at, duration_minutes
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(meeting_id, name) DO UPDATE SET
    first_joined_at = excluded.first_joined_at,
    last_left_at = excluded.last_left_at,
    duration_minutes = excluded.duration_minutes
`

type UpsertParticipantParams struct {
	MeetingID       int64        `db:"meeting_id" json:"meeting_id"`
	Name            string       `db:"name" json:"name"`
	FirstJoinedAt   time.Time    `db:"first_joined_at" json:"first_joined_at"`
	LastLeftAt      sql.NullTime `db:"last_left_at" json:"last_left_at"`
	DurationMinutes int64        `db:"duration_minutes" json:"duration_minutes"`
}

func (q *Queries) UpsertParticipant(ctx context.Context, arg UpsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, upsertParticipant,
		arg.MeetingID,
		arg.Name,
		arg.FirstJoinedAt,
		arg.LastLeftAt,
		arg.DurationMinutes,
	)
	return err
}
