// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectGoogleMeet() {
  return window['go']['main']['App']['ConnectGoogleMeet']();
}

export function ConnectOneNote() {
  return window['go']['main']['App']['ConnectOneNote']();
}

export function CreateLessonJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLessonJob'](arg1, arg2, arg3);
}

export function DisconnectGoogleMeet() {
  return window['go']['main']['App']['DisconnectGoogleMeet']();
}

export function ExportAndSavePDF(arg1) {
  return window['go']['main']['App']['ExportAndSavePDF'](arg1);
}

export function GenerateRemediation(arg1) {
  return window['go']['main']['App']['GenerateRemediation'](arg1);
}

export function GetAssignmentForGrading(arg1) {
  return window['go']['main']['App']['GetAssignmentForGrading'](arg1);
}

export function GetDashboard(arg1) {
  return window['go']['main']['App']['GetDashboard'](arg1);
}

export function GetLessonDraft(arg1) {
  return window['go']['main']['App']['GetLessonDraft'](arg1);
}

export function GetStudentDetail(arg1, arg2) {
  return window['go']['main']['App']['GetStudentDetail'](arg1, arg2);
}

export function GradeAssignment(arg1) {
  return window['go']['main']['App']['GradeAssignment'](arg1);
}

export function IsGoogleConnected() {
  return window['go']['main']['App']['IsGoogleConnected']();
}

export function IsOneNoteConnected() {
  return window['go']['main']['App']['IsOneNoteConnected']();
}

export function ListAIModels() {
  return window['go']['main']['App']['ListAIModels']();
}

export function ListGradingPages(arg1) {
  return window['go']['main']['App']['ListGradingPages'](arg1);
}

export function ListLessonDrafts() {
  return window['go']['main']['App']['ListLessonDrafts']();
}

export function ListStudentChoices() {
  return window['go']['main']['App']['ListStudentChoices']();
}

export function ListStudentMistakes() {
  return window['go']['main']['App']['ListStudentMistakes']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function PublishLessonToOneNote(arg1) {
  return window['go']['main']['App']['PublishLessonToOneNote'](arg1);
}

export function PushAssignmentFeedback(arg1) {
  return window['go']['main']['App']['PushAssignmentFeedback'](arg1);
}

export function SaveLessonDraft(arg1) {
  return window['go']['main']['App']['SaveLessonDraft'](arg1);
}

export function SyncGoogleMeet() {
  return window['go']['main']['App']['SyncGoogleMeet']();
}

export function UpdateStudent(arg1) {
  return window['go']['main']['App']['UpdateStudent'](arg1);
}
