// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {domain} from '../models';

export function ConnectGoogleMeet():Promise<void>;

export function ConnectOneNote():Promise<void>;

export function CreateLessonJob(arg1:string,arg2:string,arg3:string):Promise<number>;

export function DisconnectGoogleMeet():Promise<void>;

export function ExportAndSavePDF(arg1:number):Promise<void>;

export function GenerateRemediation(arg1:application.GenerateRemediationCommand):Promise<void>;

export function GetAssignmentForGrading(arg1:string):Promise<domain.Assignment>;

export function GetDashboard(arg1:application.StudentFilter):Promise<application.DashboardView>;

export function GetLessonDraft(arg1:number):Promise<domain.LessonDraft>;

export function GetStudentDetail(arg1:number,arg2:application.MeetingFilter):Promise<application.StudentDetailView>;

export function GradeAssignment(arg1:application.GradeAssignmentCommand):Promise<void>;

export function IsGoogleConnected():Promise<boolean>;

export function IsOneNoteConnected():Promise<boolean>;

export function ListAIModels():Promise<Array<domain.AIModelInfo>>;

export function ListGradingPages(arg1:application.GradingPageFilter):Promise<Array<application.AssignmentSummary>>;

export function ListLessonDrafts():Promise<Array<domain.LessonDraft>>;

export function ListStudentChoices():Promise<Array<application.StudentChoice>>;

export function ListStudentMistakes():Promise<Array<application.StudentMistakeGroup>>;

export function ListWorkspaces():Promise<Array<domain.Workspace>>;

export function PublishLessonToOneNote(arg1:application.PublishLessonCommand):Promise<void>;

export function PushAssignmentFeedback(arg1:string):Promise<void>;

export function SaveLessonDraft(arg1:domain.LessonDraft):Promise<void>;

export function SyncGoogleMeet():Promise<void>;

export function UpdateStudent(arg1:domain.Student):Promise<void>;
